/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountStatementConnectionInput } from './accountStatementConnectionInput';
import { AccountStatementConnectionType } from './accountStatementConnectionType';

/**
* Data for the magento proxy connection.
*/
export class AccountStatementMagentoProxyConnectionInput extends AccountStatementConnectionInput {
    'accountId': string;
    'companyId': string;
    'statementId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "companyId",
            "baseName": "companyId",
            "type": "string"
        },
        {
            "name": "statementId",
            "baseName": "statementId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AccountStatementMagentoProxyConnectionInput.attributeTypeMap);
    }
}

export namespace AccountStatementMagentoProxyConnectionInput {
}
