/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MoneyInput } from './moneyInput';

/**
* The input to create a new account statement invoice.
*/
export class AccountStatementInvoiceCreateInput {
    'amountPaid': MoneyInput;
    'amountRemaining': MoneyInput;
    'invoiceDate'?: Date;
    'reference': string;
    'total': MoneyInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountPaid",
            "baseName": "amountPaid",
            "type": "MoneyInput"
        },
        {
            "name": "amountRemaining",
            "baseName": "amountRemaining",
            "type": "MoneyInput"
        },
        {
            "name": "invoiceDate",
            "baseName": "invoiceDate",
            "type": "Date"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "MoneyInput"
        }    ];

    static getAttributeTypeMap() {
        return AccountStatementInvoiceCreateInput.attributeTypeMap;
    }
}

