/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountStatementConnectionInput } from './accountStatementConnectionInput';
import { AccountStatementCreditNoteCreateInput } from './accountStatementCreditNoteCreateInput';
import { AccountStatementInvoiceCreateInput } from './accountStatementInvoiceCreateInput';

/**
* The input to create a new account statement.
*/
export class AccountStatementCreateInput {
    'connection'?: AccountStatementConnectionInput;
    /**
    * The credit notes of the account statement.
    */
    'creditNotes'?: Array<AccountStatementCreditNoteCreateInput>;
    /**
    * The invoices of the account statement.
    */
    'invoices'?: Array<AccountStatementInvoiceCreateInput>;
    /**
    * The reference of the account statement.
    */
    'reference'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "connection",
            "baseName": "connection",
            "type": "AccountStatementConnectionInput"
        },
        {
            "name": "creditNotes",
            "baseName": "creditNotes",
            "type": "Array<AccountStatementCreditNoteCreateInput>"
        },
        {
            "name": "invoices",
            "baseName": "invoices",
            "type": "Array<AccountStatementInvoiceCreateInput>"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountStatementCreateInput.attributeTypeMap;
    }
}

