/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountStatementInvoiceStatus } from './accountStatementInvoiceStatus';
import { Money } from './money';

/**
* An account statement invoice.
*/
export class AccountStatementInvoice {
    'amountPaid': Money;
    'amountPending': Money;
    'amountRemaining': Money;
    /**
    * A list of successful checkouts that have been made for the invoice.
    */
    'checkoutIds': Set<string>;
    /**
    * The due date of the invoice.
    */
    'dueDate': Date;
    /**
    * The unique ID of the invoice.
    */
    'id': string;
    /**
    * The created date of the invoice.
    */
    'invoiceDate': Date;
    /**
    * The ID of the merchant that owns the invoice.
    */
    'merchantId': string;
    /**
    * Key value pairs to store additional information about the invoice.
    */
    'metadata': { [key: string]: string; };
    /**
    * The date the invoice was fully paid.
    */
    'paidDate'?: Date;
    /**
    * A list of checkouts that have in progress pending payments for the invoice.
    */
    'pendingCheckoutIds': Set<string>;
    /**
    * The reference of the invoice.
    */
    'reference': string;
    'status': AccountStatementInvoiceStatus;
    'taxAmount': Money;
    'total': Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountPaid",
            "baseName": "amountPaid",
            "type": "Money"
        },
        {
            "name": "amountPending",
            "baseName": "amountPending",
            "type": "Money"
        },
        {
            "name": "amountRemaining",
            "baseName": "amountRemaining",
            "type": "Money"
        },
        {
            "name": "checkoutIds",
            "baseName": "checkoutIds",
            "type": "Set<string>"
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "invoiceDate",
            "baseName": "invoiceDate",
            "type": "Date"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "paidDate",
            "baseName": "paidDate",
            "type": "Date"
        },
        {
            "name": "pendingCheckoutIds",
            "baseName": "pendingCheckoutIds",
            "type": "Set<string>"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountStatementInvoiceStatus"
        },
        {
            "name": "taxAmount",
            "baseName": "taxAmount",
            "type": "Money"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return AccountStatementInvoice.attributeTypeMap;
    }
}

export namespace AccountStatementInvoice {
}
