/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The action performed
*/
export enum ActionType {
    GlobalPaymentMethodUpdated = <any> 'GLOBAL_PAYMENT_METHOD_UPDATED',
    MerchantCreated = <any> 'MERCHANT_CREATED',
    MerchantDetailsUpdated = <any> 'MERCHANT_DETAILS_UPDATED',
    MerchantLegalDetailsCreated = <any> 'MERCHANT_LEGAL_DETAILS_CREATED',
    MerchantLegalDetailsUpdated = <any> 'MERCHANT_LEGAL_DETAILS_UPDATED',
    MerchantStatusUpdated = <any> 'MERCHANT_STATUS_UPDATED',
    MerchantOnboardingCompleted = <any> 'MERCHANT_ONBOARDING_COMPLETED',
    MerchantClientUpdated = <any> 'MERCHANT_CLIENT_UPDATED',
    MerchantPluginActivated = <any> 'MERCHANT_PLUGIN_ACTIVATED',
    MerchantPluginDeactivated = <any> 'MERCHANT_PLUGIN_DEACTIVATED',
    MerchantPricingRateCreated = <any> 'MERCHANT_PRICING_RATE_CREATED',
    MerchantUserAdded = <any> 'MERCHANT_USER_ADDED',
    MerchantUserUpdated = <any> 'MERCHANT_USER_UPDATED',
    MerchantWebhookCreated = <any> 'MERCHANT_WEBHOOK_CREATED',
    MerchantWebhookUpdated = <any> 'MERCHANT_WEBHOOK_UPDATED',
    MerchantPaymentMethodUpdated = <any> 'MERCHANT_PAYMENT_METHOD_UPDATED',
    MerchantPaymentMethodConnectionUpdated = <any> 'MERCHANT_PAYMENT_METHOD_CONNECTION_UPDATED',
    MerchantAddressUpdated = <any> 'MERCHANT_ADDRESS_UPDATED',
    MerchantBankAccountUpdated = <any> 'MERCHANT_BANK_ACCOUNT_UPDATED',
    MerchantCredentialsCreated = <any> 'MERCHANT_CREDENTIALS_CREATED',
    MerchantCredentialsDeleted = <any> 'MERCHANT_CREDENTIALS_DELETED',
    MerchantCredentialsRequested = <any> 'MERCHANT_CREDENTIALS_REQUESTED',
    MerchantCredentialsSecretRotated = <any> 'MERCHANT_CREDENTIALS_SECRET_ROTATED',
    MerchantAccountingReportDownload = <any> 'MERCHANT_ACCOUNTING_REPORT_DOWNLOAD',
    MerchantApplePayRegistered = <any> 'MERCHANT_APPLE_PAY_REGISTERED',
    MerchantApplePayUnregistered = <any> 'MERCHANT_APPLE_PAY_UNREGISTERED',
    MerchantPrimaryEmailUpdated = <any> 'MERCHANT_PRIMARY_EMAIL_UPDATED',
    MerchantUserPoliciesUpdated = <any> 'MERCHANT_USER_POLICIES_UPDATED',
    PassfortCompanyProfileFetched = <any> 'PASSFORT_COMPANY_PROFILE_FETCHED',
    MerchantKycApproved = <any> 'MERCHANT_KYC_APPROVED',
    MerchantKycStatusUpdated = <any> 'MERCHANT_KYC_STATUS_UPDATED',
    MerchantModulrCustomerCreated = <any> 'MERCHANT_MODULR_CUSTOMER_CREATED',
    MerchantModulrCustomerUpdated = <any> 'MERCHANT_MODULR_CUSTOMER_UPDATED',
    MerchantModulrAccountCreated = <any> 'MERCHANT_MODULR_ACCOUNT_CREATED',
    MerchantModulrAccountUpdated = <any> 'MERCHANT_MODULR_ACCOUNT_UPDATED',
    MerchantStatementExported = <any> 'MERCHANT_STATEMENT_EXPORTED',
    OnboardingApplicantCreated = <any> 'ONBOARDING_APPLICANT_CREATED',
    OnboardingApplicantUpdated = <any> 'ONBOARDING_APPLICANT_UPDATED',
    ApplicantStatusUpdated = <any> 'APPLICANT_STATUS_UPDATED',
    OnNetworkGlobalSettingUpdated = <any> 'ON_NETWORK_GLOBAL_SETTING_UPDATED',
    OnNetworkMerchantSettingUpdated = <any> 'ON_NETWORK_MERCHANT_SETTING_UPDATED',
    OrderCreated = <any> 'ORDER_CREATED',
    OrderUpdated = <any> 'ORDER_UPDATED',
    OrderStatusChange = <any> 'ORDER_STATUS_CHANGE',
    OrderReportDownload = <any> 'ORDER_REPORT_DOWNLOAD',
    PaymentCreated = <any> 'PAYMENT_CREATED',
    PaymentUpdated = <any> 'PAYMENT_UPDATED',
    UserEmailUpdated = <any> 'USER_EMAIL_UPDATED',
    UserCreated = <any> 'USER_CREATED',
    UserPasswordChanged = <any> 'USER_PASSWORD_CHANGED',
    UserPasswordChangeRequested = <any> 'USER_PASSWORD_CHANGE_REQUESTED',
    UserLogout = <any> 'USER_LOGOUT',
    IdentityProviderUserCreated = <any> 'IDENTITY_PROVIDER_USER_CREATED',
    Auth0UserCreated = <any> 'AUTH0_USER_CREATED',
    Auth0UserUpdated = <any> 'AUTH0_USER_UPDATED',
    LedgerManualAdjustment = <any> 'LEDGER_MANUAL_ADJUSTMENT',
    LedgerReversal = <any> 'LEDGER_REVERSAL',
    UserConsentGiven = <any> 'USER_CONSENT_GIVEN',
    PaymentLinkCreated = <any> 'PAYMENT_LINK_CREATED',
    PaymentLinkUpdated = <any> 'PAYMENT_LINK_UPDATED',
    ReimbursementCreated = <any> 'REIMBURSEMENT_CREATED',
    FeeDeleted = <any> 'FEE_DELETED',
    CheckoutCreated = <any> 'CHECKOUT_CREATED',
    CheckoutUpdated = <any> 'CHECKOUT_UPDATED',
    CheckoutTemplateCreated = <any> 'CHECKOUT_TEMPLATE_CREATED',
    CheckoutTemplateUpdated = <any> 'CHECKOUT_TEMPLATE_UPDATED',
    MerchantCommunicationPreferencesUpdated = <any> 'MERCHANT_COMMUNICATION_PREFERENCES_UPDATED',
    ThemeCreated = <any> 'THEME_CREATED',
    ThemeUpdated = <any> 'THEME_UPDATED',
    DocumentCreated = <any> 'DOCUMENT_CREATED',
    DocumentUpdated = <any> 'DOCUMENT_UPDATED',
    AccountStatementCreated = <any> 'ACCOUNT_STATEMENT_CREATED',
    AccountStatementUpdated = <any> 'ACCOUNT_STATEMENT_UPDATED',
    AccountStatementPluginPageVisited = <any> 'ACCOUNT_STATEMENT_PLUGIN_PAGE_VISITED'
}
