/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The action performed
*/
export enum ActionTypeInput {
    MerchantPluginActivated = <any> 'MERCHANT_PLUGIN_ACTIVATED',
    MerchantPluginDeactivated = <any> 'MERCHANT_PLUGIN_DEACTIVATED',
    AccountStatementPluginPageVisited = <any> 'ACCOUNT_STATEMENT_PLUGIN_PAGE_VISITED'
}
