/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The source of the application.
*/
export enum ApplicationSource {
    Api = <any> 'API',
    Xero = <any> 'XERO',
    Moto = <any> 'MOTO',
    DashboardMoto = <any> 'DASHBOARD_MOTO',
    DashboardPaymentLink = <any> 'DASHBOARD_PAYMENT_LINK',
    MagentoMoto = <any> 'MAGENTO_MOTO',
    MagentoPaymentLink = <any> 'MAGENTO_PAYMENT_LINK',
    PayNowInPerson = <any> 'PAY_NOW_IN_PERSON',
    PayNowMoto = <any> 'PAY_NOW_MOTO',
    PayNowPaymentLink = <any> 'PAY_NOW_PAYMENT_LINK'
}
