/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CheckoutApplePaySettings } from './checkoutApplePaySettings';
import { CheckoutCardSettings } from './checkoutCardSettings';
import { CheckoutGooglePaySettings } from './checkoutGooglePaySettings';
import { CheckoutPayByBankSettings } from './checkoutPayByBankSettings';

/**
* The payment method settings to be used for the checkout.
*/
export class CheckoutPaymentMethodSettings {
    'applePay'?: CheckoutApplePaySettings;
    'card'?: CheckoutCardSettings;
    'googlePay'?: CheckoutGooglePaySettings;
    'payByBank'?: CheckoutPayByBankSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "applePay",
            "baseName": "applePay",
            "type": "CheckoutApplePaySettings"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "CheckoutCardSettings"
        },
        {
            "name": "googlePay",
            "baseName": "googlePay",
            "type": "CheckoutGooglePaySettings"
        },
        {
            "name": "payByBank",
            "baseName": "payByBank",
            "type": "CheckoutPayByBankSettings"
        }    ];

    static getAttributeTypeMap() {
        return CheckoutPaymentMethodSettings.attributeTypeMap;
    }
}

