/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The customer field type.
*/
export enum CheckoutCustomerFieldType {
    GivenName = <any> 'GIVEN_NAME',
    Surname = <any> 'SURNAME',
    Email = <any> 'EMAIL',
    PhoneNumber = <any> 'PHONE_NUMBER',
    BillingAddress = <any> 'BILLING_ADDRESS'
}
