/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CheckoutApplePaySettingsUpdateInput } from './checkoutApplePaySettingsUpdateInput';
import { CheckoutCardSettingsUpdateInput } from './checkoutCardSettingsUpdateInput';
import { CheckoutGooglePaySettingsUpdateInput } from './checkoutGooglePaySettingsUpdateInput';
import { CheckoutPayByBankSettingsUpdateInput } from './checkoutPayByBankSettingsUpdateInput';

/**
* The payment method settings to be used for the checkout.
*/
export class CheckoutPaymentMethodSettingsUpdateInput {
    'applePay'?: CheckoutApplePaySettingsUpdateInput;
    'card'?: CheckoutCardSettingsUpdateInput;
    'googlePay'?: CheckoutGooglePaySettingsUpdateInput;
    'payByBank'?: CheckoutPayByBankSettingsUpdateInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "applePay",
            "baseName": "applePay",
            "type": "CheckoutApplePaySettingsUpdateInput"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "CheckoutCardSettingsUpdateInput"
        },
        {
            "name": "googlePay",
            "baseName": "googlePay",
            "type": "CheckoutGooglePaySettingsUpdateInput"
        },
        {
            "name": "payByBank",
            "baseName": "payByBank",
            "type": "CheckoutPayByBankSettingsUpdateInput"
        }    ];

    static getAttributeTypeMap() {
        return CheckoutPaymentMethodSettingsUpdateInput.attributeTypeMap;
    }
}

