/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The reference type for the checkout. This can be fixed or editable. If editable, the user can modify the reference when they pay inside the hosted checkout. 
*/
export enum CheckoutReferenceType {
    Fixed = <any> 'FIXED',
    Editable = <any> 'EDITABLE'
}
