/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApplicationSource } from './applicationSource';
import { CheckoutAmountType } from './checkoutAmountType';
import { CheckoutCustomerFields } from './checkoutCustomerFields';
import { CheckoutMode } from './checkoutMode';
import { CheckoutPaymentMethodSettings } from './checkoutPaymentMethodSettings';
import { CheckoutReferenceType } from './checkoutReferenceType';
import { PaymentMethod } from './paymentMethod';

export class CheckoutTemplate {
    'amountType': CheckoutAmountType;
    /**
    * The datetime when the checkout template was created.
    */
    'createdAt': Date;
    'customerFields'?: CheckoutCustomerFields;
    /**
    * Ordered list of payment methods that are enabled for the checkout.
    */
    'enabledPaymentMethods'?: Array<PaymentMethod>;
    /**
    * The unique ID of the checkout template.
    */
    'id': string;
    /**
    * The ID of the merchant that owns this checkout template.
    */
    'merchantId': string;
    'mode': CheckoutMode;
    /**
    * The name of the checkout template.
    */
    'name': string;
    /**
    * Whether the customer should be notified on payment completion.
    */
    'notifyCustomer': boolean;
    /**
    * Whether you should be notified on payment completion.
    */
    'notifyMerchant': boolean;
    'paymentMethodSettings'?: CheckoutPaymentMethodSettings;
    'referenceType': CheckoutReferenceType;
    'source': ApplicationSource;
    /**
    * The datetime when the checkout template was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountType",
            "baseName": "amountType",
            "type": "CheckoutAmountType"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "customerFields",
            "baseName": "customerFields",
            "type": "CheckoutCustomerFields"
        },
        {
            "name": "enabledPaymentMethods",
            "baseName": "enabledPaymentMethods",
            "type": "Array<PaymentMethod>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "CheckoutMode"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "notifyCustomer",
            "baseName": "notifyCustomer",
            "type": "boolean"
        },
        {
            "name": "notifyMerchant",
            "baseName": "notifyMerchant",
            "type": "boolean"
        },
        {
            "name": "paymentMethodSettings",
            "baseName": "paymentMethodSettings",
            "type": "CheckoutPaymentMethodSettings"
        },
        {
            "name": "referenceType",
            "baseName": "referenceType",
            "type": "CheckoutReferenceType"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "ApplicationSource"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return CheckoutTemplate.attributeTypeMap;
    }
}

export namespace CheckoutTemplate {
}
