/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CheckoutApplePaySettingsInput } from './checkoutApplePaySettingsInput';
import { CheckoutCardSettingsInput } from './checkoutCardSettingsInput';
import { CheckoutPayByBankSettingsInput } from './checkoutPayByBankSettingsInput';

/**
* The payment method settings to be used for the checkout.
*/
export class CheckoutPaymentMethodSettingsInput {
    'applePay'?: CheckoutApplePaySettingsInput;
    'card'?: CheckoutCardSettingsInput;
    'payByBank'?: CheckoutPayByBankSettingsInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "applePay",
            "baseName": "applePay",
            "type": "CheckoutApplePaySettingsInput"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "CheckoutCardSettingsInput"
        },
        {
            "name": "payByBank",
            "baseName": "payByBank",
            "type": "CheckoutPayByBankSettingsInput"
        }    ];

    static getAttributeTypeMap() {
        return CheckoutPaymentMethodSettingsInput.attributeTypeMap;
    }
}

