/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Address } from './address';
import { ApplicationSource } from './applicationSource';
import { CheckoutMode } from './checkoutMode';
import { CheckoutStatus } from './checkoutStatus';
import { Customer } from './customer';
import { Item } from './item';
import { Money } from './money';

/**
* Checkout object
*/
export class Checkout {
    'amount'?: Money;
    'billingAddress'?: Address;
    /**
    * The ID of the checkout template to use for this checkout.
    */
    'checkoutTemplateId': string;
    /**
    * The datetime when the checkout was created.
    */
    'createdAt': Date;
    'customer'?: Customer;
    /**
    * The datetime when the checkout will expire.
    */
    'expiresAt': Date;
    /**
    * The unique ID of the checkout.
    */
    'id': string;
    'items': Array<Item>;
    /**
    * The ID of the merchant that owns this checkout.
    */
    'merchantId': string;
    /**
    * Key value pairs to store additional information about the checkout.
    */
    'metadata': { [key: string]: string; };
    'mode': CheckoutMode;
    /**
    * Id related to this checkout mode. The associated AccountStatement\'s id for the ACCOUNT_STATEMENT mode.The associated PaymentLink\'s id for the PAYMENT_LINK mode.The checkout\'s id for the CHECKOUT and VIRTUAL_TERMINAL mode.
    */
    'modeId': string;
    /**
    * The ID of the payment link that was used to create this checkout.This field is deprecated and will be removed in a future version.Use the modeId field instead.
    */
    'paymentLinkId'?: string;
    /**
    * The IDs of the payment sessions that were created for this checkout.
    */
    'paymentSessionIds': Array<string>;
    /**
    * Your reference to identify the checkout and the subsequently created payment sessions.
    */
    'reference'?: string;
    'source': ApplicationSource;
    'status': CheckoutStatus;
    /**
    * The URL to redirect the customer to after the checkout is completed successfully.
    */
    'successUrl'?: string;
    /**
    * The datetime when the checkout was last updated.
    */
    'updatedAt': Date;
    /**
    * The URL to the hosted checkout page.
    */
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Money"
        },
        {
            "name": "billingAddress",
            "baseName": "billingAddress",
            "type": "Address"
        },
        {
            "name": "checkoutTemplateId",
            "baseName": "checkoutTemplateId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "Customer"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Item>"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "CheckoutMode"
        },
        {
            "name": "modeId",
            "baseName": "modeId",
            "type": "string"
        },
        {
            "name": "paymentLinkId",
            "baseName": "paymentLinkId",
            "type": "string"
        },
        {
            "name": "paymentSessionIds",
            "baseName": "paymentSessionIds",
            "type": "Array<string>"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "ApplicationSource"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CheckoutStatus"
        },
        {
            "name": "successUrl",
            "baseName": "successUrl",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Checkout.attributeTypeMap;
    }
}

export namespace Checkout {
}
