/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionDataInput } from './connectionDataInput';

/**
* The input to create a new connection.
*/
export class ConnectionCreateInput {
    'data': ConnectionDataInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "ConnectionDataInput"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionCreateInput.attributeTypeMap;
    }
}

