/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Indicates whether payment settings query is for express checkout product or cart.
*/
export enum ExpressCheckoutDisplayIntent {
    Cart = <any> 'CART',
    Product = <any> 'PRODUCT',
    Generic = <any> 'GENERIC'
}
