/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionDataInput } from './connectionDataInput';
import { ConnectionType } from './connectionType';

/**
* Data for the google pay connection.
*/
export class GooglePayConnectionDataInput extends ConnectionDataInput {
    'externalMerchantId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externalMerchantId",
            "baseName": "externalMerchantId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(GooglePayConnectionDataInput.attributeTypeMap);
    }
}

export namespace GooglePayConnectionDataInput {
}
