/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ImageUrl } from './imageUrl';

/**
* The image with a list of URLs for the different dimensions.
*/
export class Image {
    /**
    * The ID of the image document.
    */
    'documentId': string;
    'urls': Array<ImageUrl>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "urls",
            "baseName": "urls",
            "type": "Array<ImageUrl>"
        }    ];

    static getAttributeTypeMap() {
        return Image.attributeTypeMap;
    }
}

