/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ItemRestriction } from './itemRestriction';
import { MoneyInput } from './moneyInput';

/**
* An item that the customer is purchasing.
*/
export class ItemInput {
    /**
    * The name of the item.
    */
    'name': string;
    'price': MoneyInput;
    'priceWithTax'?: MoneyInput;
    /**
    * The quantity of the item being purchased.
    */
    'quantity': string;
    'restriction'?: ItemRestriction;
    /**
    * Stock keeping unit - the unique identifier for the item.
    */
    'sku': string;
    'tax'?: MoneyInput;
    'total': MoneyInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "MoneyInput"
        },
        {
            "name": "priceWithTax",
            "baseName": "priceWithTax",
            "type": "MoneyInput"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "string"
        },
        {
            "name": "restriction",
            "baseName": "restriction",
            "type": "ItemRestriction"
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "MoneyInput"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "MoneyInput"
        }    ];

    static getAttributeTypeMap() {
        return ItemInput.attributeTypeMap;
    }
}

export namespace ItemInput {
}
