/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ItemRestriction } from './itemRestriction';
import { Money } from './money';

/**
* List of items that the customer is purchasing.
*/
export class Item {
    /**
    * The datetime when the item was created.
    */
    'createdAt': Date;
    /**
    * The unique ID for the item.
    */
    'id': string;
    /**
    * The name of the item.
    */
    'name': string;
    'price': Money;
    'priceWithTax'?: Money;
    /**
    * The quantity of the item being purchased.
    */
    'quantity': string;
    'restriction': ItemRestriction;
    /**
    * Stock keeping unit - the unique identifier for the item.
    */
    'sku': string;
    'tax'?: Money;
    'total': Money;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Money"
        },
        {
            "name": "priceWithTax",
            "baseName": "priceWithTax",
            "type": "Money"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "string"
        },
        {
            "name": "restriction",
            "baseName": "restriction",
            "type": "ItemRestriction"
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "Money"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "Money"
        }    ];

    static getAttributeTypeMap() {
        return Item.attributeTypeMap;
    }
}

export namespace Item {
}
