/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Indicator of restrictions on the item. Some payment methods are unavailable for restricted items.
*/
export enum ItemRestriction {
    Allowed = <any> 'ALLOWED',
    Restricted = <any> 'RESTRICTED',
    Prohibited = <any> 'PROHIBITED'
}
