/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionData } from './connectionData';
import { ConnectionType } from './connectionType';

/**
* Data for the Klarna connection.
*/
export class KlarnaConnectionData extends ConnectionData {
    'apiPassword'?: string;
    'apiUsername'?: string;
    'displayName': string;
    'sdkClientIdentifier'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiPassword",
            "baseName": "apiPassword",
            "type": "string"
        },
        {
            "name": "apiUsername",
            "baseName": "apiUsername",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "sdkClientIdentifier",
            "baseName": "sdkClientIdentifier",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(KlarnaConnectionData.attributeTypeMap);
    }
}

export namespace KlarnaConnectionData {
}
