/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionDataInput } from './connectionDataInput';
import { ConnectionType } from './connectionType';

/**
* Data for the klarna connection.
*/
export class KlarnaConnectionDataInput extends ConnectionDataInput {
    'apiPassword': string;
    'apiUsername': string;
    'sdkClientIdentifier': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiPassword",
            "baseName": "apiPassword",
            "type": "string"
        },
        {
            "name": "apiUsername",
            "baseName": "apiUsername",
            "type": "string"
        },
        {
            "name": "sdkClientIdentifier",
            "baseName": "sdkClientIdentifier",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(KlarnaConnectionDataInput.attributeTypeMap);
    }
}

export namespace KlarnaConnectionDataInput {
}
