/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionDataInput } from './connectionDataInput';
import { ConnectionOauthSignatureMethod } from './connectionOauthSignatureMethod';
import { ConnectionType } from './connectionType';

/**
* Data for the magento proxy connection.
*/
export class MagentoProxyConnectionDataInput extends ConnectionDataInput {
    'accessToken': string;
    'accessTokenSecret': string;
    'baseUrl': string;
    'consumerKey': string;
    'consumerSecret': string;
    'oauthSignatureMethod'?: ConnectionOauthSignatureMethod;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string"
        },
        {
            "name": "accessTokenSecret",
            "baseName": "accessTokenSecret",
            "type": "string"
        },
        {
            "name": "baseUrl",
            "baseName": "baseUrl",
            "type": "string"
        },
        {
            "name": "consumerKey",
            "baseName": "consumerKey",
            "type": "string"
        },
        {
            "name": "consumerSecret",
            "baseName": "consumerSecret",
            "type": "string"
        },
        {
            "name": "oauthSignatureMethod",
            "baseName": "oauthSignatureMethod",
            "type": "ConnectionOauthSignatureMethod"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MagentoProxyConnectionDataInput.attributeTypeMap);
    }
}

export namespace MagentoProxyConnectionDataInput {
}
