/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Merchant logo with urls
*/
export class MerchantLogoWithUrls {
    /**
    * Logo document id
    */
    'documentId': string;
    /**
    * Logo in 104x104 size
    */
    'size104x104': string;
    /**
    * Logo in 40x40 size
    */
    'size40x40': string;
    /**
    * Logo in 80x80 size
    */
    'size80x80': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "size104x104",
            "baseName": "size104x104",
            "type": "string"
        },
        {
            "name": "size40x40",
            "baseName": "size40x40",
            "type": "string"
        },
        {
            "name": "size80x80",
            "baseName": "size80x80",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MerchantLogoWithUrls.attributeTypeMap;
    }
}

