/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MoneyInput {
    /**
    * The amount as a string.
    */
    'amount': string;
    /**
    * The three-letter ISO-4217 currency code of the amount.
    */
    'currency': MoneyInput.CurrencyEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "MoneyInput.CurrencyEnum"
        }    ];

    static getAttributeTypeMap() {
        return MoneyInput.attributeTypeMap;
    }
}

export namespace MoneyInput {
    export enum CurrencyEnum {
        Gbp = <any> 'GBP'
    }
}
