/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The notification type.
*/
export enum NotificationType {
    PendingRefunds = <any> 'MERCHANT_PENDING_REFUNDS',
    FailedRefunds = <any> 'MERCHANT_FAILED_REFUNDS',
    FailedSendPaymentLinkNotification = <any> 'MERCHANT_FAILED_SEND_PAYMENT_LINK_NOTIFICATION',
    PaymentCompleted = <any> 'MERCHANT_PAYMENT_COMPLETED',
    PaymentDeclined = <any> 'MERCHANT_PAYMENT_DECLINED',
    RefundSucceeded = <any> 'MERCHANT_REFUND_SUCCEEDED',
    PaymentVoided = <any> 'MERCHANT_PAYMENT_VOIDED',
    WeekendDisbursementReport = <any> 'MERCHANT_WEEKEND_DISBURSEMENT_REPORT'
}
