/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NotificationSubscriptionConfiguration } from './notificationSubscriptionConfiguration';
import { NotificationSubscriptionRecipient } from './notificationSubscriptionRecipient';

/**
* Notification subscription.
*/
export class NotificationSubscription {
    /**
    * Datetime from when the subscription is active.
    */
    'activeFrom': Date;
    /**
    * Optional end datetime for the subscription.
    */
    'activeTo'?: Date;
    /**
    * List of notification configurations for the subscription.
    */
    'configurations': Array<NotificationSubscriptionConfiguration>;
    /**
    * The datetime when the entity was created.
    */
    'createdAt': Date;
    /**
    * The id of the subscription.
    */
    'id': string;
    /**
    * Whether main contact of the merchant is included in the recipients.
    */
    'includeMainContact': boolean;
    /**
    * Whether the subscription is currently active.
    */
    'isActive': boolean;
    /**
    * The name of the subscription.
    */
    'name': string;
    /**
    * List of notification recipients for the subscription.
    */
    'recipients': Array<NotificationSubscriptionRecipient>;
    /**
    * The datetime when the entity was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "activeFrom",
            "baseName": "activeFrom",
            "type": "Date"
        },
        {
            "name": "activeTo",
            "baseName": "activeTo",
            "type": "Date"
        },
        {
            "name": "configurations",
            "baseName": "configurations",
            "type": "Array<NotificationSubscriptionConfiguration>"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "includeMainContact",
            "baseName": "includeMainContact",
            "type": "boolean"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<NotificationSubscriptionRecipient>"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return NotificationSubscription.attributeTypeMap;
    }
}

