/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NotificationType } from './notificationType';

/**
* Notification subscription configuration entry.The configuration defines the type of a notification and what channels it should be delivered on.
*/
export class NotificationSubscriptionConfiguration {
    /**
    * Allowed channels for this notification type.
    */
    'allowedChannels': Array<NotificationSubscriptionConfiguration.AllowedChannelsEnum>;
    'id': string;
    'notificationType': NotificationType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowedChannels",
            "baseName": "allowedChannels",
            "type": "Array<NotificationSubscriptionConfiguration.AllowedChannelsEnum>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "notificationType",
            "baseName": "notificationType",
            "type": "NotificationType"
        }    ];

    static getAttributeTypeMap() {
        return NotificationSubscriptionConfiguration.attributeTypeMap;
    }
}

export namespace NotificationSubscriptionConfiguration {
    export enum AllowedChannelsEnum {
        Email = <any> 'EMAIL',
        Sms = <any> 'SMS'
    }
}
