/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApplicationSource } from './applicationSource';
import { Money } from './money';
import { PaymentLinkStatus } from './paymentLinkStatus';

/**
* Payment link object
*/
export class PaymentLink {
    'amount'?: Money;
    /**
    * The IDs of the checkouts that were created for this payment link.
    */
    'checkoutIds': Array<string>;
    /**
    * The ID of the checkout template to use for this payment link.                          If not provided, the default template will be used.
    */
    'checkoutTemplateId'?: string;
    /**
    * The datetime when the payment link was created.
    */
    'createdAt': Date;
    /**
    * The unique ID of the payment link.
    */
    'id': string;
    /**
    * The ID of the merchant that owns this checkout.
    */
    'merchantId': string;
    /**
    * Your reference to identify the payment link and subsequently created checkouts                          and payment sessions.
    */
    'reference'?: string;
    /**
    * Whether the payment link can be reused for multiple payments.
    */
    'reusable': boolean;
    'source': ApplicationSource;
    'status': PaymentLinkStatus;
    /**
    * The datetime when the payment link was last updated.
    */
    'updatedAt': Date;
    /**
    * The URL to the hosted payment link page.
    */
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Money"
        },
        {
            "name": "checkoutIds",
            "baseName": "checkoutIds",
            "type": "Array<string>"
        },
        {
            "name": "checkoutTemplateId",
            "baseName": "checkoutTemplateId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "reusable",
            "baseName": "reusable",
            "type": "boolean"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "ApplicationSource"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PaymentLinkStatus"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentLink.attributeTypeMap;
    }
}

export namespace PaymentLink {
}
