/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PagePaymentMethodDetail } from './pagePaymentMethodDetail';
import { PaymentSettingsMerchant } from './paymentSettingsMerchant';

/**
* Payment Settings object
*/
export class PaymentSettings {
    'merchant': PaymentSettingsMerchant;
    'paymentMethods': PagePaymentMethodDetail;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchant",
            "baseName": "merchant",
            "type": "PaymentSettingsMerchant"
        },
        {
            "name": "paymentMethods",
            "baseName": "paymentMethods",
            "type": "PagePaymentMethodDetail"
        }    ];

    static getAttributeTypeMap() {
        return PaymentSettings.attributeTypeMap;
    }
}

