/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The settlement status of the payment.
*/
export enum PaymentSettlementStatus {
    NotInitiated = <any> 'NOT_INITIATED',
    Accepted = <any> 'ACCEPTED',
    Settled = <any> 'SETTLED',
    FundsReceived = <any> 'FUNDS_RECEIVED',
    SettledExternally = <any> 'SETTLED_EXTERNALLY'
}
