/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentActionMethod } from './paymentActionMethod';
import { PaymentActionType } from './paymentActionType';

/**
* The list of actions that can be performed on the payment.
*/
export class PaymentAction {
    'method': PaymentActionMethod;
    'type': PaymentActionType;
    'value': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "PaymentActionMethod"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentActionType"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentAction.attributeTypeMap;
    }
}

export namespace PaymentAction {
}
