/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodAssetType } from './paymentMethodAssetType';

/**
* Payment method assets object
*/
export class PaymentMethodAsset {
    'assetType': PaymentMethodAssetType;
    'attributes': { [key: string]: string; };
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "assetType",
            "baseName": "assetType",
            "type": "PaymentMethodAssetType"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodAsset.attributeTypeMap;
    }
}

export namespace PaymentMethodAsset {
}
