/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The reason the payment was voided.
*/
export enum PaymentVoidReason {
    CustomerRequest = <any> 'CUSTOMER_REQUEST',
    MerchantRequest = <any> 'MERCHANT_REQUEST',
    SuspectedFraud = <any> 'SUSPECTED_FRAUD',
    StockIssues = <any> 'STOCK_ISSUES',
    InvalidData = <any> 'INVALID_DATA'
}
