/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Payment method total limit object. Contains min and max limits for a currency.
*/
export class PaymentMethodTotalLimit {
    'currency': string;
    'max': string;
    'min': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "string"
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodTotalLimit.attributeTypeMap;
    }
}

