/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The type of the payment action.
*/
export enum PaymentActionType {
    Authorization = <any> 'AUTHORIZATION',
    Capture = <any> 'CAPTURE',
    Cancel = <any> 'CANCEL',
    ConfirmAuthorization = <any> 'CONFIRM_AUTHORIZATION',
    Card3DsAuthentication = <any> 'CARD_3DS_AUTHENTICATION'
}
