/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Address } from './address';
import { ExpressCheckoutDisplayIntent } from './expressCheckoutDisplayIntent';
import { MoneyInput } from './moneyInput';

/**
* Input for payment settings.
*/
export class PaymentSettingsContext {
    'billingAddress'?: Address;
    'checkoutId'?: string;
    'expressCheckoutDisplayIntent'?: ExpressCheckoutDisplayIntent;
    'isForDigitalDownloads'?: boolean;
    'shippingAddress'?: Address;
    'total'?: MoneyInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "billingAddress",
            "baseName": "billingAddress",
            "type": "Address"
        },
        {
            "name": "checkoutId",
            "baseName": "checkoutId",
            "type": "string"
        },
        {
            "name": "expressCheckoutDisplayIntent",
            "baseName": "expressCheckoutDisplayIntent",
            "type": "ExpressCheckoutDisplayIntent"
        },
        {
            "name": "isForDigitalDownloads",
            "baseName": "isForDigitalDownloads",
            "type": "boolean"
        },
        {
            "name": "shippingAddress",
            "baseName": "shippingAddress",
            "type": "Address"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "MoneyInput"
        }    ];

    static getAttributeTypeMap() {
        return PaymentSettingsContext.attributeTypeMap;
    }
}

export namespace PaymentSettingsContext {
}
