/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodTotalLimit } from './paymentMethodTotalLimit';

/**
* Payment method limits object. Contains expiration date and restrictions on the total for a currency.
*/
export class PaymentMethodLimit {
    'expiresAt': Date;
    'total': Array<PaymentMethodTotalLimit>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "Array<PaymentMethodTotalLimit>"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethodLimit.attributeTypeMap;
    }
}

