/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The status of the payment method.
*/
export enum PaymentMethodStatus {
    Enabled = <any> 'ENABLED',
    Disabled = <any> 'DISABLED',
    Unavailable = <any> 'UNAVAILABLE',
    Suspended = <any> 'SUSPENDED'
}
