/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddressInput } from './addressInput';
import { CustomerInput } from './customerInput';
import { ItemInput } from './itemInput';
import { MoneyInput } from './moneyInput';
import { PaymentCaptureType } from './paymentCaptureType';
import { PaymentMethod } from './paymentMethod';
import { PaymentType } from './paymentType';

/**
* Input for creating a payment session.
*/
export class PaymentSessionCreateInput {
    'billingAddress'?: AddressInput;
    'customer'?: CustomerInput;
    'discountTotal'?: MoneyInput;
    /**
    * Your reference to identify the payment session.
    */
    'externalReference'?: string;
    /**
    * List of items that the customer is purchasing.
    */
    'items'?: Array<ItemInput>;
    'metadata'?: { [key: string]: string; };
    /**
    * The URL that the customer was on when the payment session was created.
    */
    'originUrl'?: string;
    'paymentCaptureType'?: PaymentCaptureType;
    'paymentMethod': PaymentMethod;
    'paymentType'?: PaymentType;
    /**
    * Whether the customer is required to provide a shipping address.
    */
    'requiresShipping'?: boolean = false;
    /**
    * The unique identifier for the payment session. If the same session key has been used,                          the existing payment session will be updated with the new values.
    */
    'sessionKey': string;
    'shippingAddress'?: AddressInput;
    'shippingTotal'?: MoneyInput;
    'taxTotal'?: MoneyInput;
    'total': MoneyInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "billingAddress",
            "baseName": "billingAddress",
            "type": "AddressInput"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "CustomerInput"
        },
        {
            "name": "discountTotal",
            "baseName": "discountTotal",
            "type": "MoneyInput"
        },
        {
            "name": "externalReference",
            "baseName": "externalReference",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ItemInput>"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "originUrl",
            "baseName": "originUrl",
            "type": "string"
        },
        {
            "name": "paymentCaptureType",
            "baseName": "paymentCaptureType",
            "type": "PaymentCaptureType"
        },
        {
            "name": "paymentMethod",
            "baseName": "paymentMethod",
            "type": "PaymentMethod"
        },
        {
            "name": "paymentType",
            "baseName": "paymentType",
            "type": "PaymentType"
        },
        {
            "name": "requiresShipping",
            "baseName": "requiresShipping",
            "type": "boolean"
        },
        {
            "name": "sessionKey",
            "baseName": "sessionKey",
            "type": "string"
        },
        {
            "name": "shippingAddress",
            "baseName": "shippingAddress",
            "type": "AddressInput"
        },
        {
            "name": "shippingTotal",
            "baseName": "shippingTotal",
            "type": "MoneyInput"
        },
        {
            "name": "taxTotal",
            "baseName": "taxTotal",
            "type": "MoneyInput"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "MoneyInput"
        }    ];

    static getAttributeTypeMap() {
        return PaymentSessionCreateInput.attributeTypeMap;
    }
}

export namespace PaymentSessionCreateInput {
}
