/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The status of the payment session.
*/
export enum PaymentSessionStatus {
    Cancelled = <any> 'CANCELLED',
    Declined = <any> 'DECLINED',
    Expired = <any> 'EXPIRED',
    Pending = <any> 'PENDING',
    RequiresAction = <any> 'REQUIRES_ACTION',
    RequiresPayment = <any> 'REQUIRES_PAYMENT',
    Succeeded = <any> 'SUCCEEDED'
}
