/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Address } from './address';
import { CheckoutMode } from './checkoutMode';
import { Customer } from './customer';
import { Item } from './item';
import { Money } from './money';
import { Payment } from './payment';
import { PaymentSessionStatus } from './paymentSessionStatus';

export class PaymentSession {
    'billingAddress'?: Address;
    /**
    * The ID of the checkout that the payment session was created from.
    */
    'checkoutId'?: string;
    'checkoutMode': CheckoutMode;
    'checkoutModeId'?: string;
    /**
    * The datetime when the payment session was created.
    */
    'createdAt': Date;
    'customer'?: Customer;
    /**
    * The URL to the merchant dashboard for the payment session.
    */
    'dashboardUrl': string;
    'discountTotal'?: Money;
    /**
    * Your reference to identify the payment session.
    */
    'externalReference'?: string;
    /**
    * The unique ID for the payment session.
    */
    'id': string;
    /**
    * List of items that the customer is purchasing.
    */
    'items': Array<Item>;
    /**
    * The ID of the merchant that the payment session was created for.
    */
    'merchantId': string;
    /**
    * The URL that the customer was on when the payment session was created.
    */
    'originUrl'?: string;
    /**
    * The ID of the payment link that the payment session was created from.
    */
    'paymentLinkId'?: string;
    /**
    * List of payments that have been made for the payment session.
    */
    'payments': Array<Payment>;
    /**
    * Whether the customer is required to provide a shipping address.
    */
    'requiresShipping'?: boolean;
    'shippingAddress'?: Address;
    'shippingTotal'?: Money;
    'status': PaymentSessionStatus;
    'taxTotal'?: Money;
    'total': Money;
    /**
    * The datetime when the payment session was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "billingAddress",
            "baseName": "billingAddress",
            "type": "Address"
        },
        {
            "name": "checkoutId",
            "baseName": "checkoutId",
            "type": "string"
        },
        {
            "name": "checkoutMode",
            "baseName": "checkoutMode",
            "type": "CheckoutMode"
        },
        {
            "name": "checkoutModeId",
            "baseName": "checkoutModeId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "Customer"
        },
        {
            "name": "dashboardUrl",
            "baseName": "dashboardUrl",
            "type": "string"
        },
        {
            "name": "discountTotal",
            "baseName": "discountTotal",
            "type": "Money"
        },
        {
            "name": "externalReference",
            "baseName": "externalReference",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Item>"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "originUrl",
            "baseName": "originUrl",
            "type": "string"
        },
        {
            "name": "paymentLinkId",
            "baseName": "paymentLinkId",
            "type": "string"
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<Payment>"
        },
        {
            "name": "requiresShipping",
            "baseName": "requiresShipping",
            "type": "boolean"
        },
        {
            "name": "shippingAddress",
            "baseName": "shippingAddress",
            "type": "Address"
        },
        {
            "name": "shippingTotal",
            "baseName": "shippingTotal",
            "type": "Money"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PaymentSessionStatus"
        },
        {
            "name": "taxTotal",
            "baseName": "taxTotal",
            "type": "Money"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "Money"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return PaymentSession.attributeTypeMap;
    }
}

export namespace PaymentSession {
}
