/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MerchantLogoWithUrls } from './merchantLogoWithUrls';

/**
* Merchant details
*/
export class PaymentSettingsMerchant {
    /**
    * Merchant\'s id
    */
    'id': string;
    'logo'?: MerchantLogoWithUrls;
    /**
    * Merchant\'s name
    */
    'name': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "MerchantLogoWithUrls"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentSettingsMerchant.attributeTypeMap;
    }
}

