/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Money } from './money';
import { PaymentMethod } from './paymentMethod';
import { RefundFailureReason } from './refundFailureReason';
import { RefundStatus } from './refundStatus';

/**
* A refund.
*/
export class Refund {
    'amount': Money;
    /**
    * The datetime when the refund was created.
    */
    'createdAt': Date;
    'failureReason'?: RefundFailureReason;
    /**
    * The unique ID for the refund.
    */
    'id': string;
    /**
    * The merchant ID that the refund was created for.
    */
    'merchantId': string;
    /**
    * The payment ID that the refund was created for.
    */
    'paymentId': string;
    'paymentMethod': PaymentMethod;
    /**
    * The payment session ID that the refund was created for.
    */
    'paymentSessionId': string;
    /**
    * The reason for the refund.
    */
    'reason'?: string;
    'status': RefundStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Money"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "failureReason",
            "baseName": "failureReason",
            "type": "RefundFailureReason"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "paymentId",
            "baseName": "paymentId",
            "type": "string"
        },
        {
            "name": "paymentMethod",
            "baseName": "paymentMethod",
            "type": "PaymentMethod"
        },
        {
            "name": "paymentSessionId",
            "baseName": "paymentSessionId",
            "type": "string"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RefundStatus"
        }    ];

    static getAttributeTypeMap() {
        return Refund.attributeTypeMap;
    }
}

export namespace Refund {
}
