/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The reason for the refund failure.
*/
export enum RefundFailureReason {
    AmountLimitsExceeded = <any> 'AMOUNT_LIMITS_EXCEEDED',
    InsufficientFunds = <any> 'INSUFFICIENT_FUNDS',
    PaymentDisputed = <any> 'PAYMENT_DISPUTED'
}
