/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The resource an action was performed upon
*/
export enum ResourceType {
    GlobalPaymentMethod = <any> 'GlobalPaymentMethod',
    Applicant = <any> 'Applicant',
    User = <any> 'User',
    Merchant = <any> 'Merchant',
    MerchantLegalDetails = <any> 'MerchantLegalDetails',
    MerchantUser = <any> 'MerchantUser',
    MerchantPaymentMethod = <any> 'MerchantPaymentMethod',
    MerchantPricingRate = <any> 'MerchantPricingRate',
    MerchantAddress = <any> 'MerchantAddress',
    MerchantBankAccount = <any> 'MerchantBankAccount',
    MerchantCredentials = <any> 'MerchantCredentials',
    MerchantWebhook = <any> 'MerchantWebhook',
    Onboarding = <any> 'Onboarding',
    OnNetworkGlobalSetting = <any> 'OnNetworkGlobalSetting',
    OnNetworkMerchantSetting = <any> 'OnNetworkMerchantSetting',
    Order = <any> 'Order',
    Payment = <any> 'Payment',
    Ledger = <any> 'Ledger',
    MerchantAccountingReport = <any> 'MerchantAccountingReport',
    PaymentLink = <any> 'PaymentLink',
    Reimbursement = <any> 'Reimbursement',
    Fee = <any> 'Fee',
    Checkout = <any> 'Checkout',
    CheckoutTemplate = <any> 'CheckoutTemplate',
    Theme = <any> 'Theme',
    Document = <any> 'Document',
    AccountStatement = <any> 'AccountStatement'
}
