/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Date range for the export.
*/
export class StartEnd {
    'end': Date;
    'start': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "end",
            "baseName": "end",
            "type": "Date"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return StartEnd.attributeTypeMap;
    }
}

