/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StartEnd } from './startEnd';

/**
* Request statement export.
*/
export class StatementExportRequest {
    'disbursementBatchId'?: string;
    /**
    * Format for export.
    */
    'exportFormat': StatementExportRequest.ExportFormatEnum;
    'range'?: StartEnd;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "disbursementBatchId",
            "baseName": "disbursementBatchId",
            "type": "string"
        },
        {
            "name": "exportFormat",
            "baseName": "exportFormat",
            "type": "StatementExportRequest.ExportFormatEnum"
        },
        {
            "name": "range",
            "baseName": "range",
            "type": "StartEnd"
        }    ];

    static getAttributeTypeMap() {
        return StatementExportRequest.attributeTypeMap;
    }
}

export namespace StatementExportRequest {
    export enum ExportFormatEnum {
        OfxV2 = <any> 'OFX_V2'
    }
}
