/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ThemeColors } from './themeColors';
import { ThemePaymentMethodSelector } from './themePaymentMethodSelector';

/**
* Theme object
*/
export class Theme {
    'colors': ThemeColors;
    /**
    * The datetime when the theme was created.
    */
    'createdAt': Date;
    /**
    * The unique ID of the theme.
    */
    'id': string;
    /**
    * Whether the theme is the default theme that is used when no theme is specified.
    */
    'isDefault': boolean;
    /**
    * The ID of the merchant that the theme belongs to.
    */
    'merchantId': string;
    /**
    * The name of the theme.
    */
    'name': string;
    'paymentMethodSelector': ThemePaymentMethodSelector;
    /**
    * The datetime when the theme was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "colors",
            "baseName": "colors",
            "type": "ThemeColors"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isDefault",
            "baseName": "isDefault",
            "type": "boolean"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "paymentMethodSelector",
            "baseName": "paymentMethodSelector",
            "type": "ThemePaymentMethodSelector"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Theme.attributeTypeMap;
    }
}

