/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Theme payment method selector colors update input
*/
export class ThemePaymentMethodSelectorColorsUpdateInput {
    /**
    * The border color.
    */
    'background'?: string;
    /**
    * The background color.
    */
    'border'?: string;
    /**
    * The hover background color.
    */
    'hoverBackground'?: string;
    /**
    * The hover text color.
    */
    'hoverText'?: string;
    /**
    * The text color.
    */
    'text'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "background",
            "baseName": "background",
            "type": "string"
        },
        {
            "name": "border",
            "baseName": "border",
            "type": "string"
        },
        {
            "name": "hoverBackground",
            "baseName": "hoverBackground",
            "type": "string"
        },
        {
            "name": "hoverText",
            "baseName": "hoverText",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ThemePaymentMethodSelectorColorsUpdateInput.attributeTypeMap;
    }
}

