/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The background image for mobile with the URLs for the different dimensions.
*/
export class ThemeMobileBackgroundImage {
    /**
    * The ID of the image document.
    */
    'documentId': string;
    /**
    * The URL for the image with the size 1920x1080.
    */
    'size1920x1080': string;
    /**
    * The URL for the image with the size 420x800.
    */
    'size420x800': string;
    /**
    * The URL for the image with the size 768x1024.
    */
    'size768x1024': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "size1920x1080",
            "baseName": "size1920x1080",
            "type": "string"
        },
        {
            "name": "size420x800",
            "baseName": "size420x800",
            "type": "string"
        },
        {
            "name": "size768x1024",
            "baseName": "size768x1024",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ThemeMobileBackgroundImage.attributeTypeMap;
    }
}

