/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ThemePaymentMethodSelectorColorsUpdateInput } from './themePaymentMethodSelectorColorsUpdateInput';

/**
* Theme payment method selector update input
*/
export class ThemePaymentMethodSelectorUpdateInput {
    'colors': ThemePaymentMethodSelectorColorsUpdateInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "colors",
            "baseName": "colors",
            "type": "ThemePaymentMethodSelectorColorsUpdateInput"
        }    ];

    static getAttributeTypeMap() {
        return ThemePaymentMethodSelectorUpdateInput.attributeTypeMap;
    }
}

