/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ThemeImageCreateInput } from './themeImageCreateInput';

/**
* The background images for the theme.
*/
export class ThemeBackgroundImageCreateInput {
    'desktop'?: ThemeImageCreateInput;
    'mobile'?: ThemeImageCreateInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "desktop",
            "baseName": "desktop",
            "type": "ThemeImageCreateInput"
        },
        {
            "name": "mobile",
            "baseName": "mobile",
            "type": "ThemeImageCreateInput"
        }    ];

    static getAttributeTypeMap() {
        return ThemeBackgroundImageCreateInput.attributeTypeMap;
    }
}

