/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ThemeImageUpdateInput } from './themeImageUpdateInput';

/**
* Theme background image update input.                      Explicitly setting any of the fields to `null` will remove the image.
*/
export class ThemeBackgroundImageUpdateInput {
    'desktop'?: ThemeImageUpdateInput;
    'mobile'?: ThemeImageUpdateInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "desktop",
            "baseName": "desktop",
            "type": "ThemeImageUpdateInput"
        },
        {
            "name": "mobile",
            "baseName": "mobile",
            "type": "ThemeImageUpdateInput"
        }    ];

    static getAttributeTypeMap() {
        return ThemeBackgroundImageUpdateInput.attributeTypeMap;
    }
}

