/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ThemeColorsUpdateInput } from './themeColorsUpdateInput';
import { ThemePaymentMethodSelectorUpdateInput } from './themePaymentMethodSelectorUpdateInput';

/**
* Theme update input
*/
export class ThemeUpdateInput {
    'colors'?: ThemeColorsUpdateInput;
    /**
    * Whether the theme is the default theme that is used when no theme is specified.
    */
    'isDefault'?: boolean;
    /**
    * The name of the theme.
    */
    'name'?: string;
    'paymentMethodSelector'?: ThemePaymentMethodSelectorUpdateInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "colors",
            "baseName": "colors",
            "type": "ThemeColorsUpdateInput"
        },
        {
            "name": "isDefault",
            "baseName": "isDefault",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "paymentMethodSelector",
            "baseName": "paymentMethodSelector",
            "type": "ThemePaymentMethodSelectorUpdateInput"
        }    ];

    static getAttributeTypeMap() {
        return ThemeUpdateInput.attributeTypeMap;
    }
}

