/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The event type of the webhook.
*/
export enum WebhookEventType {
    PaymentAuthorized = <any> 'PAYMENT_AUTHORIZED',
    PaymentCompleted = <any> 'PAYMENT_COMPLETED',
    PaymentSucceeded = <any> 'PAYMENT_SUCCEEDED',
    RefundCompleted = <any> 'REFUND_COMPLETED',
    RefundSucceeded = <any> 'REFUND_SUCCEEDED'
}
