/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WebhookEventType } from './webhookEventType';
import { WebhookStatus } from './webhookStatus';

export class Webhook {
    /**
    * Custom headers for the webhook.
    */
    'headers': { [key: string]: string; };
    /**
    * The unique ID of the webhook.
    */
    'id': string;
    /**
    * The ID of the merchant that the webhook belongs to.
    */
    'merchantId': string;
    'status': WebhookStatus;
    /**
    * The events that the webhook is subscribed to.
    */
    'subscribedEvents': Set<WebhookEventType>;
    /**
    * The URL to send the webhook events to.
    */
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "WebhookStatus"
        },
        {
            "name": "subscribedEvents",
            "baseName": "subscribedEvents",
            "type": "Set<WebhookEventType>"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Webhook.attributeTypeMap;
    }
}

export namespace Webhook {
}
