/**
 * Rvvup API
 * Rvvup Public API
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: info@rvvup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WebhookEventType } from './webhookEventType';
import { WebhookStatus } from './webhookStatus';

/**
* The input for updating a webhook.
*/
export class WebhookUpdateInput {
    /**
    * Custom headers for the webhook
    */
    'headers'?: { [key: string]: string | null; } | null;
    'status'?: WebhookStatus;
    /**
    * The events to subscribe to.
    */
    'subscribedEvents'?: Set<WebhookEventType>;
    /**
    * The URL to send the webhook event to.
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: string | null; }"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "WebhookStatus"
        },
        {
            "name": "subscribedEvents",
            "baseName": "subscribedEvents",
            "type": "Set<WebhookEventType>"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WebhookUpdateInput.attributeTypeMap;
    }
}

export namespace WebhookUpdateInput {
}
